### ISSUE TITLE
[v1] Toolbar active state is inconsistent

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-img#49] opened 2017-03-27 23:33 UTC
The toolbar active states will go out of sync with the editor's state e.g. creating a link in the editor, then moving the toolbar elsewhere the link will still apparently be active in the toolbar.

Another case is when initially bolding via the toolbar, the bold button does not go active even though it's been applied.

The sync between toolbar state and editor state should in general be simplified.

**Comment by seaneking** [comment] 2017-03-28 14:26
Ahh wrong repo @bedeoverend ;-)

Dupe of https://github.com/SimplaElements/simpla-text/issues/37 regardless

**Closed by seaneking** 2017-03-28 14:26 UTC

**Comment by bedeoverend** [comment] 2017-03-28 19:34
Oh whoops - no wonder I couldn't find an issue already 😉
